version: '3.7'

services:
  # traefik:
  #   image: traefik:v2.10.4
  #   container_name: traefik
  #   ports:
  #     - 80:80
  #   command:
  #     - "--api.insecure=true"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #     - "--log.level=DEBUG"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   restart: unless-stopped
  dedigi2-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # expose:
    #   - 8000
    ports:
      - 8000:8000
    restart: unless-stopped
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.dedigi2-backend.rule=Host(`localhost`) && PathPrefix(`/api`)"
    #   # - "traefik.http.routers.dedigi2-backend.middlewares=dedigi2-backend-mdw"
    #   - "traefik.http.routers.dedigi2-backend.entrypoints=web"
    #   # - "traefik.http.middlewares.dedigi2-backend-mdw.stripprefix.prefixes=/api"
  dedigi2:
    build:
      context: .
      dockerfile: Dockerfile
    # expose:
    #   - 3000
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dedigi2.rule=Host(`localhost`)"
      - "traefik.http.routers.dedigi2.entrypoints=web"